version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: Scripts/Install_nginix.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts/start_nginix.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_nginix.sh
    - location: Scripts/start_nginix.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/start_nginix.sh
      timeout: 300
      runas: root
